<?php
$this->headTitle('View Blog - ' . $blog->getTitle());

$this->mainMenu()->setActiveItemId('home');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);
        
?>

<a href="
    <?= $this->url('application', ['action'=>'index']); ?>">
    &lt;&lt; Back to list of blogs
</a>

<h1>
    <?= $this->escapeHtml($blog->getTitle()); ?>
</h1>

